export enum QuestionType {
  TEXT = "TEXT",
  MULTIPLE_CHOICE = "MULTIPLE_CHOICE",
  RATING_MATRIX = "RATING_MATRIX",
  DROPDOWN = "DROPDOWN",
  RANKING = "RANKING",
  IMAGE_CHOICE = "IMAGE_CHOICE",
  FILE_UPLOAD = "FILE_UPLOAD"
}
